### PR TITLE
porting pointcoud_to_pcd to ros2

### PR DESCRIPTION
**Pull request by Ar-Ray-code**
I needed the ROS 2 version of pointcoud_to_pcd, so I will port it and submit a PR.
Please review.

## Depends
- ROS 2 Humble (on Ubuntu22.04 LTS, x86-64)

## Usage
- subscriber topic (pointcloud2) : /cloud_in
- prefix : abc_
- fixed_frame (central frame_id) : base_link

```bash
ros2 run pcl_ros pointcloud_to_pcd --ros-args -r input:=/cloud_in -p prefix:=abc_ -p fixed_frame:=base_link
```

### How to check exported pcd file

```bash
pcl_viewer <path to .pcd file>
```

image

Thank you.

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]
LGTM from a quick glance. From your testing image I assume this works fine

**Comment by SteveMacenski** [comment]
Were there tests associated with this as well? 

Otherwise, give this a week and if no other maintainers chime in, ping me again and I'll merge it

**Review by remco-r — COMMENTED** [review]
builds for humble (not for foxy)
features tested
- prefix
- compresed
- binary
- prefix
- fixed_frame

`ros2 run pcl_ros pointcloud_to_pcd --ros-args -r input:=os_node/points -p prefix:=abc_ -p binary:=true -p compressed:=true -p fixed_frame:=base_link`

Everything works except fixed_frame feature because my (ouster) lidar frame is on tf_static i get the following error.


```
[WARN] [1712221819.952296406] [transform_listener_impl_556e0f932ee0]: New publisher discovered on topic '/tf_static', offering incompatible QoS. No messages will be sent to it. Last incompatible policy: DURABILITY_QOS_POLICY
[ERROR] [1712221820.239036841] [pointcloud_to_pcd]: Transform error: "os_sensor" passed to lookupTransform argument source_frame does not exist. 
```

**Comment by Ar-Ray-code** [comment]
> builds for humble (not for foxy) features tested
> 
> * prefix
> * compresed
> * binary
> * prefix
> * fixed_frame
> 
> `ros2 run pcl_ros pointcloud_to_pcd --ros-args -r input:=os_node/points -p prefix:=abc_ -p binary:=true -p compressed:=true -p fixed_frame:=base_link`
> 
> Everything works except fixed_frame feature because my (ouster) lidar frame is on tf_static i get the following error.
> 
> ```
> [WARN] [1712221819.952296406] [transform_listener_impl_556e0f932ee0]: New publisher discovered on topic '/tf_static', offering incompatible QoS. No messages will be sent to it. Last incompatible policy: DURABILITY_QOS_POLICY
> [ERROR] [1712221820.239036841] [pointcloud_to_pcd]: Transform error: "os_sensor" passed to lookupTransform argument source_frame does not exist. 
> ```

Thank you for your testing.

fixed_frame is an option that can be used when the sensor is connected to another tf.
For example, the following command broadcasts a relative position with x=2, yaw=90deg.

`ros2 run tf2_ros static_transform_publisher 2 0 0 0 0 0.707 0.707 base_link velodyne`

I would consider implementing the following: if tf cannot be obtained, a warning is displayed and the fixed_frame option is ignored. <- done

**Comment by Ar-Ray-code** [comment]
I also added the `rgb` option because when I tested with velodyne we could not save in RGB. (Default is false)

**Comment by SteveMacenski** [comment]
@remco-r let me know if that resolves your concern

**Comment by remco-r** [comment]
@SteveMacenski 

- The fixed_frame issue is just an observation. Its a ros2 and tf issue though, and not related to this PR. So concern resolved
- The new RGB + use_transform features added in the last two commits I havent tested, but the code looks good.

**Review by SteveMacenski — APPROVED** [review]

**Pull request merged**
