### PR TITLE
Add fixed_frame to pointcloud_to_pcd

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by paulbovbel** [comment]
If tf(2) data is not actively being broadcast in the system, this will fail, which may be problematic for users with bags or running otherwise isolated systems. Could you follow legacy behaviour when the fixed_frame parameter is not provided?

**Comment by jspricke** [comment]
Good point, fixed now.

**Comment by mintar** [comment]
@paulbovbel , any news on this?

**Comment by paulbovbel** [comment]
Where does the time go. LGTM, thanks for poking @mintar.

**Pull request merged**
