### PR TITLE
ROS 2 dashing pcl_ros port

### PR DESCRIPTION
**Pull request by sloretz**
This is still a work in progress (with a lot more work to do), but the Crop Box and Pass Through filters do work. It has everything from #229 plus changes from @mabelzhang's branch. I'm opening it for visibility.

It should build fine in Eloquent, but requires this rclcpp release to build in Dashing: https://github.com/ros/rosdistro/pull/23240

### CODE REVIEW

**Comment by SteveMacenski** [comment]
It seems like there's been alot done and that might not be a realistic to ask to separate this into smaller PRs. As long as someone has tested the basic behavior of each of the parts ported I don't see a reason to block merging it so there's "something" out there, but it will be challenging or near impossible to have too much critical feedback on a 5,000+ line, 200 files touched PR.

Are there areas this PR hasn't touched (yet) that we could rescope for either someone else to work on in parallel or at least separate into another PR so that we can break apart what we can going forward? Looking for a specific set of things that I could give people to work on in a couple bullets. Might also be good to have a ticket filed that we check off what's done in some pending PR or who's working on it

**Comment by sloretz** [comment]
> It seems like there's been alot done and that might not be a realistic to ask to separate this into smaller PRs.

Yeah there are a lot of changes now. I was expecting to split it eventually.

> Are there areas this PR hasn't touched (yet) that we could rescope for either someone else to work on in parallel or at least separate into another PR so that we can break apart what we can going forward? 

There's nothing untouched, but there's plenty that can be done in parallel. Since there's a lot of progress in this branch, I'd recommend a workflow of branching from `dashing-devel` then checking out individual files from here as a starting point.

Before that there should a PR for `pcl_ros_tf`. Afterward the tools/executables can all be done in parallel, plus each plugin category can be done in parallel (once a first PR with`pcl_node.h` changes is merged). Within a plugin category there needs to be a first example that ports the base class (filter.cpp, feature.cpp, etc) first, but once that's done porting the rest becomes much easier.

I haven't been careful about style or whitespace changes. Can I assume those can be cleaned up later?

**Comment by SteveMacenski** [comment]
Yeah, I'm not a big worrier about linting. Its not like this was clean to begin with so that's an "future improvement". Apparently @JWhitleyAStuff is a saint and enjoys that type of thing, so we might be able to rope him into doing it. If not I'm sure someone will down the line. 

> There's nothing untouched, but there's plenty that can be done in parallel. 

This sounds like merge conflict-central.

I'd prefer if we could merge this PR once its in a reasonable state to do so, then moving forward have a ticket of tasks broken down so that there's a clear separation of what's done, what's being done, and what's open to be done. But with that said, you're the one at the moment "doing the stuff" so by all means I don't want to slow you down.

**Comment by theseankelly** [comment]
Hey @sloretz -- @SteveMacenski  reached out for general help over on [discourse](https://discourse.ros.org/t/call-for-help-pcl-ros-for-ros2/15131/7) and I signed up to help.

Do you have plans/desires to rebase this work and push it through to Foxy? If so, any specific things you'd like help with? If not, I'll just dig in.

**Comment by SteveMacenski** [comment]
@theseankelly my github ID is stevemacenski not smac (side story: I tried desperately to change my discourse name to stevemacenski to fix that exact issue but couldn't figure out how). 

I think you may to dig in. All the folks at OR are very busy and if this has been sitting around for this long, I couldn't expect anything to change.

**Comment by theseankelly** [comment]
@SteveMacenski whoops sorry! Sounds good. I'll do what I can to chunk it up into smaller, more standalone PRs as I go.

**Comment by SteveMacenski** [comment]
Please, please, please do

**Comment by sloretz** [comment]
I noticed this repo has a `ros2` branch and has been released to rolling. I'll close this assuming the ROS 2 port has been completed.

**Comment by vincentrou** [comment]
@sloretz I want to point out that the release on `ros2` only concern  `pcl_ros_tf`.
There is a lot of commented library in the CMakeLists : https://github.com/ros-perception/perception_pcl/blob/ros2/pcl_ros/CMakeLists.txt
So this work is still needed.

**Pull request closed without merging**
