### PR TITLE
Just update .travis.yml for melodic

### PR DESCRIPTION
**Pull request by wkentaro**
To divide the build failure problem to following:

- current industrial_ci config is bad?
- perception_pcl cannot be built on stretch, artful, and bionic?

### CODE REVIEW

**Comment by wkentaro** [comment]
```
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
Configuring tzdata
------------------
Please select the geographic area in which you live. Subsequent configuration
questions will narrow this down by presenting a list of cities, representing
the time zones in which they are located.
  1. Africa      4. Australia  7. Atlantic  10. Pacific  13. Etc
  2. America     5. Arctic     8. Europe    11. SystemV
  3. Antarctica  6. Asia       9. Indian    12. US
Geographic area: 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```
so I added `DEBIAN_FRONTEND=noninteractive`

**Comment by wkentaro** [comment]
```
10:46:40 [WARNINGS] Parsing warnings in console log with parser CMake
10:46:41 <Git Blamer> Using GitBlamer to create author and commit information for all warnings.
10:46:41 <Git Blamer> GIT_COMMIT=66fb2412443071598201b986de8db2e6ccfb46ca, workspace=/home/jenkins-agent/workspace/Mpr__perception_pcl__ubuntu_bionic_amd64/catkin_workspace/src/perception_pcl
10:46:41 [WARNINGS] Parsing warnings in console log with parser GNU C Compiler 4 (gcc)
10:46:41 <Git Blamer> Using GitBlamer to create author and commit information for all warnings.
10:46:41 <Git Blamer> GIT_COMMIT=66fb2412443071598201b986de8db2e6ccfb46ca, workspace=/home/jenkins-agent/workspace/Mpr__perception_pcl__ubuntu_bionic_amd64/catkin_workspace/src/perception_pcl
10:46:41 <Git Blamer> Skipping non-workspace file /usr/include/pcl-1.8/pcl/sample_consensus/model_types.h (workspace = /home/jenkins-agent/workspace/Mpr__perception_pcl__ubuntu_bionic_amd64/catkin_workspace/src/perception_pcl, absolute = /usr/include/pcl-1.8/pcl/sample_consensus/model_types.h.
10:46:41  > git rev-parse 66fb2412443071598201b986de8db2e6ccfb46ca^{commit} # timeout=10
10:46:41 <Git Blamer> Skipping file /usr/include/pcl-1.8/pcl/sample_consensus/model_types.h, no result found.
10:46:41 [WARNINGS] Computing warning deltas based on reference build #20
10:46:41 [WARNINGS] Ignore new warnings since this is the first valid build
10:46:41 [WARNINGS] Plug-in Result: Unstable - <a href="warningsResult">1 warning</a> exceeds the threshold of 0 by 1
10:46:41 Build step 'Scan for compiler warnings' changed build result to UNSTABLE
10:46:41 [xUnit] [INFO] - Starting to record.
10:46:41 [xUnit] [INFO] - Processing GoogleTest-1.6
10:46:41 [xUnit] [INFO] - [GoogleTest-1.6] - 13 test report file(s) were found with the pattern 'catkin_workspace/test_results/**/*.xml' relative to '/home/jenkins-agent/workspace/Mpr__perception_pcl__ubuntu_bionic_amd64' for the testing framework 'GoogleTest-1.6'.
10:46:41 [xUnit] [INFO] - Check 'Failed Tests' threshold.
10:46:41 [xUnit] [INFO] - Check 'Skipped Tests' threshold.
10:46:41 [xUnit] [INFO] - Setting the build status to UNSTABLE
10:46:41 [xUnit] [INFO] - Stopping recording.
10:46:41 Setting status of ec9c00ff06db1796a19a1d11a8004975963f015c to FAILURE with url http://build.ros.org/job/Mpr__perception_pcl__ubuntu_bionic_amd64/22/ and message: 'Build finished. '
10:46:41 Using context: Mpr__perception_pcl__ubuntu_bionic_amd64
10:46:41 Could not update commit status of the Pull Request on GitHub.
10:46:41 org.kohsuke.github.HttpException: Server returned HTTP response code: 201, message: 'Created' for URL: https://api.github.com/repos/ros-perception/perception_pcl/statuses/ec9c00ff06db1796a19a1d11a8004975963f015c
10:46:41 	at org.kohsuke.github.Requester.parse(Requester.java:622)
10:46:41 	at org.kohsuke.github.Requester.parse(Requester.java:584)
10:46:41 	at org.kohsuke.github.Requester._to(Requester.java:264)
10:46:41 	at org.kohsuke.github.Requester.to(Requester.java:226)
10:46:41 	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:1000)
10:46:41 	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:272)
10:46:41 	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildComplete(GhprbSimpleStatus.java:231)
10:46:41 	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:192)
10:46:41 	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:26)
10:46:41 	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:211)
10:46:41 	at hudson.model.Run.execute(Run.java:1780)
10:46:41 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
10:46:41 	at hudson.model.ResourceController.execute(ResourceController.java:97)
10:46:41 	at hudson.model.Executor.run(Executor.java:405)
10:46:41 Caused by: java.io.IOException: Failed to deserialize {"url":"https://api.github.com/repos/ros-perception/perception_pcl/statuses/ec9c00ff06db1796a19a1d11a8004975963f015c","id":4904279101,"state":"failure","description":"Build finished. ","target_url":"http://build.ros.org/job/Mpr__perception_pcl__ubuntu_bionic_amd64/22/","context":"Mpr__perception_pcl__ubuntu_bionic_amd64","created_at":"2018-05-02T17:46:41Z","updated_at":"2018-05-02T17:46:41Z","creator":{"login":"ros-pull-request-builder","id":7094544,"avatar_url":"https://avatars0.githubusercontent.com/u/7094544?v=4","gravatar_id":"","url":"https://api.github.com/users/ros-pull-request-builder","html_url":"https://github.com/ros-pull-request-builder","followers_url":"https://api.github.com/users/ros-pull-request-builder/followers","following_url":"https://api.github.com/users/ros-pull-request-builder/following{/other_user}","gists_url":"https://api.github.com/users/ros-pull-request-builder/gists{/gist_id}","starred_url":"https://api.github.com/users/ros-pull-request-builder/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ros-pull-request-builder/subscriptions","organizations_url":"https://api.github.com/users/ros-pull-request-builder/orgs","repos_url":"https://api.github.com/users/ros-pull-request-builder/repos","events_url":"https://api.github.com/users/ros-pull-request-builder/events{/privacy}","received_events_url":"https://api.github.com/users/ros-pull-request-builder/received_events","type":"User","site_admin":false}}
10:46:41 	at org.kohsuke.github.Requester.parse(Requester.java:608)
10:46:41 	... 13 more
10:46:41 Caused by: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (4904279101) out of range of int
10:46:41  at [Source: {"url":"https://api.github.com/repos/ros-perception/perception_pcl/statuses/ec9c00ff06db1796a19a1d11a8004975963f015c","id":4904279101,"state":"failure","description":"Build finished. ","target_url":"http://build.ros.org/job/Mpr__perception_pcl__ubuntu_bionic_amd64/22/","context":"Mpr__perception_pcl__ubuntu_bionic_amd64","created_at":"2018-05-02T17:46:41Z","updated_at":"2018-05-02T17:46:41Z","creator":{"login":"ros-pull-request-builder","id":7094544,"avatar_url":"https://avatars0.githubusercontent.com/u/7094544?v=4","gravatar_id":"","url":"https://api.github.com/users/ros-pull-request-builder","html_url":"https://github.com/ros-pull-request-builder","followers_url":"https://api.github.com/users/ros-pull-request-builder/followers","following_url":"https://api.github.com/users/ros-pull-request-builder/following{/other_user}","gists_url":"https://api.github.com/users/ros-pull-request-builder/gists{/gist_id}","starred_url":"https://api.github.com/users/ros-pull-request-builder/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ros-pull-request-builder/subscriptions","organizations_url":"https://api.github.com/users/ros-pull-request-builder/orgs","repos_url":"https://api.github.com/users/ros-pull-request-builder/repos","events_url":"https://api.github.com/users/ros-pull-request-builder/events{/privacy}","received_events_url":"https://api.github.com/users/ros-pull-request-builder/received_events","type":"User","site_admin":false}}; line: 1, column: 134]
10:46:41  at [Source: {"url":"https://api.github.com/repos/ros-perception/perception_pcl/statuses/ec9c00ff06db1796a19a1d11a8004975963f015c","id":4904279101,"state":"failure","description":"Build finished. ","target_url":"http://build.ros.org/job/Mpr__perception_pcl__ubuntu_bionic_amd64/22/","context":"Mpr__perception_pcl__ubuntu_bionic_amd64","created_at":"2018-05-02T17:46:41Z","updated_at":"2018-05-02T17:46:41Z","creator":{"login":"ros-pull-request-builder","id":7094544,"avatar_url":"https://avatars0.githubusercontent.com/u/7094544?v=4","gravatar_id":"","url":"https://api.github.com/users/ros-pull-request-builder","html_url":"https://github.com/ros-pull-request-builder","followers_url":"https://api.github.com/users/ros-pull-request-builder/followers","following_url":"https://api.github.com/users/ros-pull-request-builder/following{/other_user}","gists_url":"https://api.github.com/users/ros-pull-request-builder/gists{/gist_id}","starred_url":"https://api.github.com/users/ros-pull-request-builder/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ros-pull-request-builder/subscriptions","organizations_url":"https://api.github.com/users/ros-pull-request-builder/orgs","repos_url":"https://api.github.com/users/ros-pull-request-builder/repos","events_url":"https://api.github.com/users/ros-pull-request-builder/events{/privacy}","received_events_url":"https://api.github.com/users/ros-pull-request-builder/received_events","type":"User","site_admin":false}}; line: 1, column: 124] (through reference chain: org.kohsuke.github.GHCommitStatus["id"])
10:46:41 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:339)
10:46:41 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:299)
10:46:41 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1511)
10:46:41 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:262)
10:46:41 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
10:46:41 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
10:46:41 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2779)
10:46:41 	at org.kohsuke.github.Requester.parse(Requester.java:606)
10:46:41 	... 13 more
10:46:41 Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (4904279101) out of range of int
10:46:41  at [Source: {"url":"https://api.github.com/repos/ros-perception/perception_pcl/statuses/ec9c00ff06db1796a19a1d11a8004975963f015c","id":4904279101,"state":"failure","description":"Build finished. ","target_url":"http://build.ros.org/job/Mpr__perception_pcl__ubuntu_bionic_amd64/22/","context":"Mpr__perception_pcl__ubuntu_bionic_amd64","created_at":"2018-05-02T17:46:41Z","updated_at":"2018-05-02T17:46:41Z","creator":{"login":"ros-pull-request-builder","id":7094544,"avatar_url":"https://avatars0.githubusercontent.com/u/7094544?v=4","gravatar_id":"","url":"https://api.github.com/users/ros-pull-request-builder","html_url":"https://github.com/ros-pull-request-builder","followers_url":"https://api.github.com/users/ros-pull-request-builder/followers","following_url":"https://api.github.com/users/ros-pull-request-builder/following{/other_user}","gists_url":"https://api.github.com/users/ros-pull-request-builder/gists{/gist_id}","starred_url":"https://api.github.com/users/ros-pull-request-builder/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ros-pull-request-builder/subscriptions","organizations_url":"https://api.github.com/users/ros-pull-request-builder/orgs","repos_url":"https://api.github.com/users/ros-pull-request-builder/repos","events_url":"https://api.github.com/users/ros-pull-request-builder/events{/privacy}","received_events_url":"https://api.github.com/users/ros-pull-request-builder/received_events","type":"User","site_admin":false}}; line: 1, column: 134]
10:46:41 	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586)
10:46:41 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521)
10:46:41 	at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:938)
10:46:41 	at com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:876)
10:46:41 	at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:704)
10:46:41 	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:313)
10:46:41 	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:293)
10:46:41 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
10:46:41 	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
10:46:41 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
10:46:41 	... 17 more
10:46:41 Finished: UNSTABLE
```
http://build.ros.org/job/Mpr__perception_pcl__ubuntu_bionic_amd64/22/console

**Comment by wkentaro** [comment]
@paulbovbel Do you have idea how to fix the error on build.ros.org?
https://github.com/ros-perception/perception_pcl/pull/197#issuecomment-386070611

Also, I'm just curious. What kind of advantages the test on `build.rog.org` has over the tests on Travis? I thought it can be disabled since the code is already tested on Travis.

**Comment by wkentaro** [comment]
It seems that the build on build.ros.org fails because of a warning when building the pcl code.
And I don't think this can be fixed in this repo, since the warning is invoked when the header file is included by the code and the warning should be removed from the code in PCL.
https://github.com/PointCloudLibrary/pcl/pull/2071

```
10:31:44 In file included from /usr/include/pcl-1.8/pcl/sample_consensus/sac_model.h:52:0,
10:31:44                  from /usr/include/pcl-1.8/pcl/sample_consensus/sac_model_plane.h:44,
10:31:44                  from /usr/include/pcl-1.8/pcl/segmentation/extract_polygonal_prism_data.h:42,
10:31:44                  from /tmp/catkin_workspace/src/perception_pcl/pcl_ros/include/pcl_ros/segmentation/extract_polygonal_prism_data.h:47,
10:31:44                  from /tmp/catkin_workspace/src/perception_pcl/pcl_ros/src/pcl_ros/segmentation/extract_polygonal_prism_data.cpp:40:
10:31:44 /usr/include/pcl-1.8/pcl/sample_consensus/model_types.h: In function ‘void __static_initialization_and_destruction_0(int, int)’:
10:31:44 /usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: warning: ‘pcl::SAC_SAMPLE_SIZE’ is deprecated: This map is deprecated and is kept only to prevent breaking existing user code. Starting from PCL 1.8.0 model sample size is a protected member of the SampleConsensusModel class [-Wdeprecated-declarations]
10:31:44    SAC_SAMPLE_SIZE (sample_size_pairs, sample_size_pairs + sizeof (sample_size_pairs) / sizeof (SampleSizeModel));
10:31:44    ^~~~~~~~~~~~~~~
10:31:44 /usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: note: declared here
```

```
10:46:41 [WARNINGS] Computing warning deltas based on reference build #20
10:46:41 [WARNINGS] Ignore new warnings since this is the first valid build
10:46:41 [WARNINGS] Plug-in Result: Unstable - <a href="warningsResult">1 warning</a> exceeds the threshold of 0 by 1
10:46:41 Build step 'Scan for compiler warnings' changed build result to UNSTABLE
```

**Review by paulbovbel — APPROVED** [review]

**Comment by wkentaro** [comment]
Rebased.

**Comment by wkentaro** [comment]
Now, the push build passed.
So I am releasing 1.6.1.
screen shot 2018-05-08 at 18 47 45

**Pull request merged**
