### PR TITLE
add excplicit dependency on gencfg target

### PR DESCRIPTION
**Pull request by dirk-thomas**
After merging please release the patch into Hydro.

### CODE REVIEW

**Comment by MichaelKorn** [comment]
William, please, can you release this patch to groovy-devel and groovy-unstable-devel? Compiling ROS Groovy from Source don't work because of this issue (http://answers.ros.org/question/81441/missing-filterconfigh-for-pcl_ros-in-groovy/)

**Comment by wjwwood** [comment]
@tfoote

**Comment by wjwwood** [comment]
I think @tfoote took care of this already.

**Comment by tfoote** [comment]
It is out in 1.1.7 including two other missing dependencies.

**Comment by MichaelKorn** [comment]
yes, it was done soon after my post. Thanks.

**Pull request merged**
