### PR TITLE
sorts pc msg fields by offset (ros2)

### LINKED ISSUE #434: PointCloud2 fields not always sorted by offset
Some ROS `sensor_msgs/PointCloud2` messages created with the functions defined in [plc_conversion.h](https://github.com/ros-perception/perception_pcl/blob/ros2/pcl_conversions/include/pcl_conversions/pcl_conversions.h) will not have the `fields` attribute sorted by offset. I don't think that is a documented requirement, so the messages are fine and readable with most tools. However, most of the time the fields are sorted in that way and it looks like some tools do assume that the field is sorted that way (for example https://github.com/eric-wieser/ros_numpy/issues/40). I believe in general would be good practice to always make sure that the fields in point cloud messages are sorted in such a way, even though it is not specified.

The issue linked above has an example of a message that is not sorted. It was created with `pcl::toROSMsg()` from a `pcl::PointXYZINormal` type point cloud object. The `curvature` and `intensity` fields are both populated as used [here](https://github.com/hku-mars/FAST_LIO). The fields look like this:

```
name: "x"
offset: 0
datatype: 7
count: 1, name: "y"
offset: 4
datatype: 7
count: 1, name: "z"
offset: 8
datatype: 7
count: 1, name: "intensity"
offset: 32
datatype: 7
count: 1, name: "normal_x"
offset: 16
datatype: 7
count: 1, name: "normal_y"
offset: 20
datatype: 7
count: 1, name: "normal_z"
offset: 24
datatype: 7
count: 1, name: "curvature"
offset: 36
datatype: 7
count: 1
```

### PR DESCRIPTION
**Pull request by cosama**
Closes https://github.com/ros-perception/perception_pcl/issues/434

This is in analogy to https://github.com/ros-perception/perception_pcl/pull/437 and fixes https://github.com/ros-perception/perception_pcl/issues/434 but for ros2. I haven't tested it locally but if it passes the tests, it should be working as expected, because the same changes were also applied to the test, which requires fields being sorted.

### CODE REVIEW

**Comment by cosama** [comment]
This has been sitting around for 6 month and more. It would be ready to be merged. Is there anything else I need to do? Happy to move this forward so that we can finish it up.

**Comment by SteveMacenski** [comment]
Personally, its a lack of my own knowledge about the ramifications of this change for the entire breadth of downstream users that makes me nervous. The sort operations also adds in additional compute / latency, which makes me think this should be an optional thing rather than always done when converting PCL pointclouds. 

@mvieth any objections with merging if its parameterized whether to include? Any reason we shouldn't do this that you can think of since you posted this block in the ticket as a recent PCL change?

**Comment by mvieth** [comment]
> Personally, its a lack of my own knowledge about the ramifications of this change for the entire breadth of downstream users that makes me nervous. The sort operations also adds in additional compute / latency, which makes me think this should be an optional thing rather than always done when converting PCL pointclouds.

I believe this additional latency is negligible since `pfs` (the vector to be sorted) is small (typically < 10 elements) and in most cases already sorted.

I also can't think of any problem the sorting might cause: in most cases, nothing changes (already sorted). In the cases where sorting does change the order, it could only cause a problem if a user assumes that a specific field is always at a fixed position in the fields vector, which is to my knowledge not guaranteed anywhere and a rather fragile behaviour (in contrast to iterating through the field vector and checking the names).

> @mvieth any objections with merging if its parameterized whether to include? Any reason we shouldn't do this that you can think of since you posted this block in the ticket as a recent PCL change?

How would you make it parameterized? What would be the default? If you are thinking about adding a parameter to the `fromPCL`  function, then `copyPCLPointCloud2MetaData` would also need a parameter (it calls `fromPCL`), as well as all functions that call `copyPCLPointCloud2MetaData`.

I have no objections, no matter if sorting is optional or always done.

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
Makes sense, merging! 

I don't work with overly sophisticated pointcloud fields, so I wanted to check in with someone else before I made a foreseeable mistake. I maintain this repository by consensus & cut the releases when asked, I'm admittedly not overly active here and mostly help as a volunteer to keep the gears moving :smile:

**Comment by SteveMacenski** [comment]
Thanks for the ping @cosama!

**Comment by cosama** [comment]
@mvieth @SteveMacenski Thank you so much for being so quick on this.

**Pull request merged**
