### PR TITLE
ROS2 port perception_pcl

### PR DESCRIPTION
**Pull request by klintan**
WIP

Wanted to keep it transparent so will start a draft PR. Doing the velodyne package which depends on this one.

Still not compiling, and will probably be working with a bit smaller feature-set before it's fully featured and working.

### CODE REVIEW

**Comment by SteveMacenski** [comment]
@klintan is this draft required with your other PR?

**Comment by klintan** [comment]
> @klintan is this draft required with your other PR?

No it is not related. This is including pcl_ros package as well,  however without type masquerading it's quite challenging, so it's on hold from my side as of now.

**Comment by SteveMacenski** [comment]
@mabelzhang you mentioned someone on your end was thinking about or in the middle of porting pcl_ros. Can you connect them with me so we can chat on the best path for this?

**Comment by mabelzhang** [comment]
@sloretz is working on porting pcl_ros. I believe there's some blending with the branch in this PR, the last I heard.

**Comment by SteveMacenski** [comment]
@sloretz you can find my email on my GitHub page (don't want to explicitly list it for the spam bots), we should chat on what you've done, doing, and in your queue so I can complement it and not have dual-work. 

I'd love to have a componentized-pcl_ros done before end of 2019

**Comment by sloretz** [comment]
> @sloretz you can find my email on my GitHub page (don't want to explicitly list it for the spam bots), we should chat on what you've done, doing, and in your queue so I can complement it and not have dual-work.

Whoops, I missed this. I opened #255 for visibility. I'm working on the filters at the moment.

**Comment by 130s** [comment]
@klintan Is this PR still supposed to be merged? If not I suggest to close (as the title could falsely give impressions that ros2 port is not done even the basic part of it).

Looking at https://github.com/ros-perception/perception_pcl/pull/255#issuecomment-1021714153 and https://github.com/ros-perception/perception_pcl/issues/225 (and maybe some others), basics seem to be completed.

**Comment by klintan** [comment]
> @klintan Is this PR still supposed to be merged? If not I suggest to close (as the title could falsely give impressions that ros2 port is not done even the basic part of it).
> 
> Looking at [#255 (comment)](https://github.com/ros-perception/perception_pcl/pull/255#issuecomment-1021714153) and #225 (and maybe some others), basics seem to be completed.

Agree, I'll close this one.

**Pull request closed without merging**
