### PR TITLE
Add nodelets definitions

### PR DESCRIPTION
**Pull request by garaemon**
revert nodelet definitions

### CODE REVIEW

**Comment by garaemon** [comment]
ping

**Comment by paulbovbel** [comment]
Sorry, was thesis writing. Thanks for the pull, no idea why those weren't defined in the first place. @wjwwood would you know why?

@LucidOne, looks good to you?

**Comment by wjwwood** [comment]
I don't know why, this was before I took over, maybe they weren't building? I would double check that they are also in the CMakeLists.txt getting built.

**Comment by garaemon** [comment]
thanks!

2014年6月26日木曜日、Paul Bovbelnotifications@github.comさんは書きました:

> Merged #58 https://github.com/ros-perception/perception_pcl/pull/58.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-perception/perception_pcl/pull/58#event-135480285
> .

## 

from iPhone

**Pull request merged**
