### PR TITLE
Fix melodic build

### PR DESCRIPTION
**Pull request by clalancette**
These 2 commits seem to fix the melodic dev build, that failed here: http://build.ros.org/view/Mdev/job/Mdev__perception_pcl__ubuntu_bionic_amd64/1/consoleFull

### CODE REVIEW

**Comment by paulbovbel** [comment]
Thanks @clalancette. What do you think of this approach (https://github.com/ros-perception/perception_pcl/pull/192/commits/7b6e086113e780a9e9617935e99b4003f92d8b24)?

I was trying to keep the dependencies transitive, since pcl_conversions is header only outside of tests.

**Comment by mikaelarguedas** [comment]
It would be great if we could make it work without escalating all the dependencies to build_depend and exec_depend and keeping them transitive instead.
have you tried the following approaches?
- make the find_package of the test depends REQUIRED and pass their LIBRARIES and INCLUDE_DIRS to the tests (e.g find_package(std_msgs REQUIRED) ... include_directories(... ${std_msgs_INCLUDE_DIRS}" ...) etc
- find the test dependencies as REQUIRED catkin components to keep using the `catkin_LIBRARIES` 
 `catkin_INCLUDE_DIRS` macros for the tests

**Comment by paulbovbel** [comment]
Opened a PR for the commit above here (https://github.com/ros-perception/perception_pcl/pull/194)

**Comment by wkentaro** [comment]
Closed via https://github.com/ros-perception/perception_pcl/pull/194

**Pull request closed without merging**
