### PR TITLE
pcl_ros: use nodelet_topic_tools::NodeletLazy

### PR DESCRIPTION
**Pull request by furushchev**
Yet another implementation of #153.

In this pull request, `pcl_ros::PCLNodelet` inherits `nodelet_topic_tools::NodeletLazy` that provides lazy subscription of input topics.
Each nodes now only subscribe topics only they have subscribers and does not consume computational resource if no subscriber exists.

### CODE REVIEW

**Comment by furushchev** [comment]
Travis failed on `debian:stretch`:

```
ERROR: the following rosdeps failed to install
  apt: command [apt-get install -y -qq libpcl-dev] failed


The command "docker run --rm -i -v $CI_SOURCE_PATH:$CI_SOURCE_PATH -e "CI_SOURCE_PATH=$CI_SOURCE_PATH" -e "HOME=$HOME" -e "ROS_DISTRO=$ROS_DISTRO" -e "ROS_PARALLEL_JOBS=$ROS_PARALLEL_JOBS" -e "DOCKER_IMAGE=$DOCKER_IMAGE" -t $DOCKER_IMAGE sh -c "cd $CI_SOURCE_PATH; ./.travis.sh"" exited with 1.
```

**Comment by wkentaro** [comment]
Please rebase.

**Comment by furushchev** [comment]
Cannot rebased with my technical git level. Merged instead.

**Comment by furushchev** [comment]
It looks like the same error on `debian:stretch`...

```
ERROR: the following rosdeps failed to install
  apt: command [apt-get install -y -qq libpcl-dev] failed

travis_time:end:02c09548:start=1502775717661243570,finish=1502775964269674463,duration=246608430893
[0K
[31;1mThe command "docker run --rm -i -v $CI_SOURCE_PATH:$CI_SOURCE_PATH -e "CI_SOURCE_PATH=$CI_SOURCE_PATH" -e "HOME=$HOME" -e "ROS_DISTRO=$ROS_DISTRO" -e "ROS_PARALLEL_JOBS=$ROS_PARALLEL_JOBS" -e "DOCKER_IMAGE=$DOCKER_IMAGE" -t $DOCKER_IMAGE sh -c "cd $CI_SOURCE_PATH; ./.travis.sh"" exited with 1.[0m
```

**Comment by mikaelarguedas** [comment]
Not sure if it'll solve your problem but maybe that'll help: we noticed on the ROS buildfarm that some debian mirrors were not up to date or not responsive. We ended up pinning down a specific CDN that we knew worked well https://github.com/ros-infrastructure/ros_buildfarm/pull/467.

**Comment by wkentaro** [comment]
@mikaelarguedas I tried using ros_buildfarm on Travis, but had following error on debian:
Do you know something about this?

https://travis-ci.org/ros-perception/perception_pcl/jobs/266946497
```
1.48s$ generate_devel_script.py https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml $ROS_DISTRO default $REPOSITORY_NAME $OS_NAME $OS_CODE_NAME $ARCH > $JOB_PATH/devel_job.sh
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.3/bin/generate_devel_script.py", line 100, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.5.3/bin/generate_devel_script.py", line 81, in main
    jenkins=False, views=False)
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/ros_buildfarm/devel_job.py", line 277, in configure_devel_job
    ', '.join(sorted(build_file.targets.keys())))
ros_buildfarm.common.JobValidationError: Invalid OS name 'debian' choose one of the following: ubuntu
```

**Comment by mikaelarguedas** [comment]
The ros_buildfarm has several types of jobs, each of them using specific build files listed in the [index](https://github.com/ros-infrastructure/ros_buildfarm_config/blob/b113c3548c8b3d0ff2dbd1d3b696714d3f9bb6c5/index.yaml). In this case you are doing a devel / source job. These jobs use the [source entry](https://github.com/ros-infrastructure/ros_buildfarm/blob/887897d13df94b6b99aa74310f348cd3e8be7149/ros_buildfarm/devel_job.py#L52) of the [index](https://github.com/ros-infrastructure/ros_buildfarm_config/blob/b113c3548c8b3d0ff2dbd1d3b696714d3f9bb6c5/index.yaml#L58).  As far as I know for all ROS distro this file contains only one os, one codename and one architecture (in the case of lunar: ubuntu xenial amd64). That is why the dev and PR jobs on the ros_buildfarm cover only this combination. So I would expect the command you used to fail for any other os (yakkety or zesty or debian stretch).

Alternative:
run prerelease jobs: these are made to test your code and downstream packages, if you want to only test your repository you can set the level of dependencies to be tested to 0. See [prerelease.ros.org](http://prerelease.ros.org/) or the [rob_buildfarm documentation](https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/jobs/prerelease_jobs.rst#run-the-prerelease-job-on-travis) for instructions/ examples of how to run them in travis.

Hope this helps

**Comment by wkentaro** [comment]
@mikaelarguedas Thank you! but it seems a little difficult to use, so I firstly change apt server url at https://github.com/ros-perception/perception_pcl/pull/156. Could you please review it?

**Comment by wkentaro** [comment]
Now this feature is merged via https://github.com/ros-perception/perception_pcl/pull/160

**Pull request closed without merging**
