### PR TITLE
Groovy unstable devel update

### PR DESCRIPTION
**Pull request by MichaelKorn**
Maybe the merge could be done better (I used: git read-tree --prefix=pcl_ros/ -u remotes/upstream/hydro-devel:pcl_ros/).

### CODE REVIEW

**Comment by wjwwood** [comment]
I would do this:

```
git clone https://github.com/MichaelKorn/perception_pcl.git
cd perception_pcl
git checkout groovy-unstable-devel
git remote add upstream https://github.com/ros-perception/perception_pcl.git
git checkout -b upstream-groovy-unstable-devel upstream/groovy-unstable-devel
git checkout groovy-unstable-devel
git rebase upstream-groovy-unstable-devel
git push -f origin groovy-unstable-devel
```

**Comment by MichaelKorn** [comment]
OK, I did this. But I don't understand the benefit and nothing was changed (git push.. -> "Everything up-to-date").

**Comment by wjwwood** [comment]
Sorry I was thinking it was a merge problem, it is that the Travis-CI failed.

**Comment by wjwwood** [comment]
@MichaelKorn You'll want to setup a `.travis.yml` file like this one:

https://github.com/ros-perception/perception_pcl/blob/hydro-devel/.travis.yml

Otherwise you can just turn off CI for this branch using, see:

http://about.travis-ci.org/docs/user/build-configuration/#White--or-blacklisting-branches

Something like this:

```
# blacklist
branches:
  except:
    - groovy-unstable-devel
```

**Comment by MichaelKorn** [comment]
Can you give me some hints how to improve my travis.yml (https://github.com/MichaelKorn/perception_pcl/blob/9ec7a157c7049b198377be5b820d9e81c6dee473/.travis.yml)?
It is not possible to use "catkin_make tests --source . -j1 -DCATKIN_ENABLE_TESTING=ON", because the package pcl contain a plain cmake file.

**Comment by wjwwood** [comment]
Do you need those packages from source? Why not just install the debians with apt-get and then build just `perception_pcl`?

**Comment by wjwwood** [comment]
You probably don't need the checkout of `pcl_msgs` and `pcl_conversions`, unless you explicitly want them from source. I would just build `pcl_ros` like this:

```
cd pcl_ros
mkdir build
cd build
source /opt/ros/hydro/setup.bash
cmake .. -DCATKIN_ENABLE_TESTING=1
make
make tests
make run_tests
catkin_test_results ./test_results
```

**Comment by MichaelKorn** [comment]
Hey wjwwood,
this is about groovy-unstable. We use this package to get the newest KinFu code in ROS (Because of this I'm more interested in perception_pcl as in pcl_ros). For our needs this package works fine and we have a working KinFu ROS package for groovy. I have just problems with Travis (and some to merge pcl_ros in the right way).

Maybe another point that can be discussed is whether groovy-unstable-devel should be updated or not, because of the huge changes: https://github.com/PointCloudLibrary/pcl/wiki/Remove-ROS. Maybe groovy-unstable-devel should be freezed at the lasted version without this changes.
We will switch to hydro, too. But we will need again a unstable package.

**Comment by wjwwood** [comment]
I can merge this now, I don't really care about the travis integration, it would just be nice to have.

**Comment by wjwwood** [comment]
I got the CI working, 1202887f226408970996248ffed2dc3490f90ba9, but it is still failing, I'm not sure your branch will compile in groovy:

https://travis-ci.org/ros-perception/perception_pcl/builds/11425969

**Pull request merged**
