### PR TITLE
Migrate extract_indices filter

### PR DESCRIPTION
**Pull request by daisukes**
This is the third PR of the migration PR series (#383)
The previous PR is #388

- migrate extract_indices.{cpp,hpp}
    CMakeLists.txt related to those files
- add tests to check if filter node/component output result

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
CI results look like your tests failed

**Comment by daisukes** [comment]
@SteveMacenski 

> CI results look like your tests failed

I didn't include fixes for existing fails of `cpplint` and `uncrustify`.
Is it better to include fixes with this PR or the next PR?

**Comment by SteveMacenski** [comment]
I'm not referring to the linting, the actual tests failed as well

**Comment by SteveMacenski** [comment]
(still failing)

**Comment by SteveMacenski** [comment]
Now only 1 of them failed!

**Comment by daisukes** [comment]
I see no more test failures. Thank you for your follow-ups!

**Pull request merged**
