### PR TITLE
incrementing version to 1.7.1 for release 

### PR DESCRIPTION
**Pull request by SteveMacenski**
Also added myself as a maintainer that was missing.

#268 and https://github.com/SteveMacenski/spatio_temporal_voxel_layer/issues/134

### CODE REVIEW

**Comment by SteveMacenski** [comment]
@paulbovbel can you approve this so I can run bloom?

**Comment by ahcorde** [comment]
is this update related with noetic? if this is the case, can you take in account this PR https://github.com/ros-perception/perception_pcl/pull/270

**Comment by paulbovbel** [comment]
@SteveMacenski, please feel free to cut releases without going through a PR process. Ideally, what's been reviewed and sitting on any *-devel branch should be good to go anytime.

**Review by paulbovbel — APPROVED** [review]

**Comment by SteveMacenski** [comment]
@ahcorde this is for melodic. Is noetic for this unblocked? I can do that as well. 

@paulbovbel I would have, but PR review even for maintainers settings is on ;-). I’ll take your response as permission to remove that restriction.

**Comment by paulbovbel** [comment]
No, please leave PR reviews on, however you can cut the release directly from the `melodic-devel` branch via catkin_generate_changelogs and catkin_prepare_release.

In fact, catkin_prepare_release wants to increment the package.xml version numbers for you in tandem with updating the changelog, so you should roll that back and generate changelogs _first_.

**Comment by SteveMacenski** [comment]
@paulbovbel I have to march the package.xml version up. I also have an existing workflow for this and I'm not going to be able to change it for just this one repo.

Edit: my issue with `catkin_prepare_release` is that it commits to the distro master branch directly. I don't allow myself to use tools that do that automatically. I've been burned before and not looking for that experience again. 

> No, please leave PR reviews on

It would still be on, its just that maintainers can use their `sudo` powers to overrule it for cases such as this, just incrementing up a number.

**Comment by paulbovbel** [comment]
> I also have an existing workflow for this and I'm not going to be able to change it for just this one repo.

Well, in that case your workflow is missing generating changelogs.

**Comment by SteveMacenski** [comment]
That is correct, I generally do not generate them unless the license requires them. I have never actually had a single person ask about or reference a changelog so I just don't bother. Alot of changelogs are lazily populated and I'd rather just be honest by not providing one than providing a shotty attempt at one.

If that's something important to you, I can work that into my workflows. I just haven't talked to anyone that valued them. Its time well spent if its something people actually use / want.

**Comment by paulbovbel** [comment]
I would appreciate including the changelogs when cutting releases. Lazily populated is better than nothing and I've found them useful.

**Pull request merged**
