### PR TITLE
[pcl_ros] Use waitForTransform and use_latest_tf_ to resolve tf

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
I added 
- `~use_latest_tf` param for fixed frames.
- `waitForTransform` to avoid error in lookup transform

**Comment by wkentaro** [comment]
ping

**Comment by SteveMacenski** [comment]
@wkentaro this looks reasonable to me, is this still something you'd like to see merged?

**Comment by SteveMacenski** [comment]
Closing from inactivity, open to merging this with support from author and CI. Reopen if interested.

**Pull request closed without merging**
