### PR TITLE
Nodelet for CropBox filter

### PR DESCRIPTION
**Pull request by martimorta**
Hi,
I have created this nodelet for the cropbox filter, it is basically a copy of the [Passthrough nodelet](http://wiki.ros.org/pcl_ros/Filters#PassThrough) using the [CropBox filter](http://docs.pointclouds.org/trunk/classpcl_1_1_crop_box_3_01pcl_1_1_p_c_l_point_cloud2_01_4.html)

I have tested it using pointcloud data from a sensor using a ROS node in a 64bit Ubuntu 12.04 machine.
If there's something wrong, please, let me know.

In case it is accepted I don't mind write the documentation in the wiki.

Thanks!

### CODE REVIEW

**Comment by paulbovbel** [comment]
@martimorta, I think the cmake_modules is unnecessary in hydro.

**Comment by martimorta** [comment]
Thanks, i'll have a look.

**Comment by martimorta** [comment]
Hi @wjwwood do you think this could be merged in the project? Thanks in advance!

**Comment by martimorta** [comment]
Thanks Paul!

**Comment by paulbovbel** [comment]
Thanks for making a pull of your code! I didn't see a notification that you'd fixed the build problem.

**Comment by tfoote** [comment]
@paulbovbel  Yeah, you don't get notifications on new commits. @martimorta make sure to comment after a fixup commit on pull requests to notify the maintainers.

**Pull request merged**
