### PR TITLE
Release 1.5.4

### LINKED ISSUE #176: Release 1.5.4 to lunar
- [x] Test nodelets
- [x] Release

### PR DESCRIPTION
**Pull request by wkentaro**
Close #176 

## Next Actions

- Create Tag 1.5.4
- Run `bloom-release`.

### CODE REVIEW

**Comment by wkentaro** [comment]
Rebased with origin/lunar-devel.

**Review by paulbovbel — APPROVED** [review]
I appreciate the diligence, but I don't think we should worry about PRs to cut a release in the future, and just release directly off '*-devel'. These branches should always be release-ready.

**Comment by wkentaro** [comment]
Ok, so can I disable the checkbox on GitHub that requires at least one review?
(actually I can't directry push to lunar-devel at current.)

**Comment by paulbovbel** [comment]
No, I mean run the `catkin_generate_changelog/catkin_prepare_release/bloom-release` commands directly from the `-devel` branch.

**Comment by wkentaro** [comment]
Sorry, maybe I don't understand.
Do you mean I didn't need to rebase with origin/lunar-devel?

**Comment by wkentaro** [comment]
I thought you meant I should type `Y` in this prompt.
```
% catkin_prepare_release
Prepare the source repository for a release.
Repository type: git
Found packages: pcl_ros, perception_pcl
Prepare release of version '1.5.4' [Y/n]?Y
Trying to push to remote repository (dry run)...
Warning: Permanently added the RSA host key for IP address '192.30.255.112' to the list of known hosts.
To git@github.com:ros-perception/perception_pcl.git
   a89e22e..6661b0e  lunar-devel -> lunar-devel
Checking if working copy is clean (no staged changes, no modified files, no untracked files)...
Rename the forthcoming section of the following packages to version '1.5.4': pcl_ros, perception_pcl
Bump version of all packages from '1.5.3' to '1.5.4'
Committing the package.xml files...
[lunar-devel 8ab2e5f] 1.5.4
 4 files changed, 6 insertions(+), 6 deletions(-)
Creating tag '1.5.4'...
The following commands will be executed to push the changes and tag to the remote repository:
  /home/wkentaro/.local/bin/git push origin lunar-devel
  /home/wkentaro/.local/bin/git push --tags
Push the local commits and tags to the remote repository [Y/n]?
```

**Comment by paulbovbel** [comment]
Sorry if I wasn't clear @wkentaro. I was just proposing that you don't need to make a branch/open a PR to cut a release, because there's really nothing to approve. I would be fine with either of us being able to freely cut a release for a distro from the associated distro-devel branch without any sort of review process.

Either way, this LGTM!

**Comment by wkentaro** [comment]
I see. Thanks!

**Pull request merged**
