### PR TITLE
Branch to release to Lunar

### PR DESCRIPTION
**Pull request by wkentaro**
Will be migrated to ros-perception:lunar-devel

- [x] xenial
- [x] yakkety
- [x] zesty

### CODE REVIEW

**Comment by wkentaro** [comment]
BTW, `find_package(PCL 1.7 REQUIRED)` can be replaced to `find_package(PCL REQUIRED)` in most cases, why is this applied on kinetic? @paulbovbel

**Comment by wkentaro** [comment]
@paulbovbel Please review this in the next to release to lunar.

**Review by paulbovbel — APPROVED** [review]
LGTM for lunar-devel

**Comment by wkentaro** [comment]
Created lunar-devel https://github.com/ros-perception/perception_pcl/tree/lunar-devel

**Comment by wkentaro** [comment]
@paulbovbel Should we make lunar-devel the default branch on GitHub?

**Comment by wkentaro** [comment]
@paulbovbel Should I need to change CHANGELOG.rst? or just run bloom?

**Comment by paulbovbel** [comment]
Yes to lunar-devel branch in github.

Are you familiar with the standard bloom process? Along the lines of:

catkin_generate_changelog
catkin_prepare_release (--bump minor for new distro)
bloom-release -r lunar -t lunar perception_pcl

If not, please read http://wiki.ros.org/bloom/Tutorials/ReleaseCatkinPackage

**Pull request closed without merging**
