### PR TITLE
Fix Travis CI builds

### PR DESCRIPTION
**Pull request by LucidOne**
mkdir ~/catkin_ws/logs manually to resolve travis build errors

### CODE REVIEW

**Comment by LucidOne** [comment]
This pull request is in progress

**Comment by LucidOne** [comment]
```
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "roscpp" with any
  of the following names:
    roscppConfig.cmake
    roscpp-config.cmake
```

It looks non-deterministic so I think the issue is rosdep is timing out on network connectivity

**Comment by paulbovbel** [comment]
I would suggest poking at industrial_ci (https://github.com/ros-perception/perception_pcl/pull/195) instead, as that's been pretty reliable in the past.

**Comment by LucidOne** [comment]
I'm 100% in favor of not running docker if we don't have to.
@wkentaro , do you want to rebase #195 or should I fork from `travis-industrial-rebased`?

**Comment by paulbovbel** [comment]
Melodic targets bionic which Travis does not support natively, so you're kind of stuck with docker.

industrial_ci is used quite extensively throughout the ROS ecosystem and 'works'.

The alternative is to drop Travis and rely on buildfarm PR builds exclusively.

**Comment by LucidOne** [comment]
Thanks. I'll see what I can come up with. Any thoughts on https://builds.sr.ht/
https://man.sr.ht/builds.sr.ht/compatibility.md

**Comment by paulbovbel** [comment]
> Any thoughts on https://builds.sr.ht/ https://man.sr.ht/builds.sr.ht/compatibility.md

Not really, other than we already have two pre-baked solutions for CI tests for a ROS package, and I'd be keen to avoid NIH given limited bandwidth for upkeep:
- ros_buildfarm
- industrial_ci via travis

**Pull request closed without merging**
