### PR TITLE
Update for Rolling file name changes

### PR DESCRIPTION
**Pull request by SteveMacenski**
Fixes some build warnings and allows packages to successfully build with conservative warnings to errors compiler flags, rolling only

### CODE REVIEW

**Comment by Timple** [comment]
This does not have to be rolling only. The changes are backwards compatible.

**Comment by Rayman** [comment]
> This does not have to be rolling only. The changes are backwards compatible.

Hmm, no? (tested on jazzy)
```
find -name '*message_traits*'
./include/message_filters/message_filters/message_traits.h
```

**Comment by Timple** [comment]
Well bloody... I do remember the discussion that this all should be backported. 

Guess I stand corrected.

**Comment by AlexandruSopt** [comment]
In my ROS2 Humble WS the error appears:
... /pcl_conversions/include/pcl_conversions/pcl_conversions.h:44:10: fatal error: message_filters/message_event.hpp: No such file or directory
   44 | #include <message_filters/message_event.hpp>
I ran all rosdep dependency checks and still can not get rid of error. If the change is rolled back from *.hpp to *.h than everything is peachy.

Bottom line: I do not think this works for ros2 humble deployments. Checked the message_filters repo and the *.hpp versions of the file are available for rolling , but not for humble.

**Pull request merged**
