### PR TITLE
Swtich to build_export_depend for libpcl-all-dev

### LINKED ISSUE #446: Regression in ROS 2 Iron Buildfarm
https://github.com/ros-perception/perception_pcl/pull/384 switched `libpcl-all-dev` from `<depend>` to `<build_depend>`.

As a result the [latest bloom release](https://github.com/ros/rosdistro/pull/40476) is causing regressions in other downstream packages such as [bosch_locator_bridge](https://build.ros2.org/view/Ibin_uJ64/job/Ibin_uJ64__bosch_locator_bridge__ubuntu_jammy_amd64__binary/32/).

```bash
CMake Error at /opt/ros/iron/share/pcl_conversions/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package):
  By not providing "FindPCL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "PCL", but
  CMake did not find one.

  Could not find a package configuration file provided by "PCL" with any of
  the following names:

    PCLConfig.cmake
    pcl-config.cmake

  Add the installation prefix of "PCL" to CMAKE_PREFIX_PATH or set "PCL_DIR"
  to a directory containing one of the above files.  If "PCL" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /opt/ros/iron/share/pcl_conversions/cmake/pcl_conversionsConfig.cmake:41 (include)
  CMakeLists.txt:26 (find_package)
```

Adding  `<build_export_depend>libpcl-all-dev</build_export_depend>` to `package.xml` should fix the issue.

### PR DESCRIPTION
**Pull request by Yadunund**
Fix #446

Once merged, a new bloom release is required.

### CODE REVIEW

**Review by Aposhian — APPROVED** [review]
LGTM!

**Review by SteveMacenski — APPROVED** [review]

**Comment by Rayman** [comment]
Due to this change the build for iron is failing:

https://build.ros2.org/job/Ibin_uJ64__pcl_conversions__ubuntu_jammy_amd64__binary/

jazzy doesn't have this commit yet
https://build.ros2.org/job/Jbin_uN64__pcl_conversions__ubuntu_noble_amd64__binary/

I think this can be solved in two ways

1. This package doesn't need any dependencies to build. It only contains headers. Therefore we move all `find_package` call to the `BUILD_TEST` section
2. `build_export_depend` doesn't pull in the dependeny during build, only for dependent packages. Therefore we can also convert the PCL dependency to a `<build>` depend tag

**Comment by SteveMacenski** [comment]
I defer to your judgement - open a PR and I can run again

Also, possibly happy to add you as a maintainer here as well so I'm not a blocker. We'd have to ask others, but I think you are diligent and well meet the criteria. Would you be interested in that?

**Comment by Rayman** [comment]
I'll open a PR for that

If you want you can add me as maintainer, I have a bit of time for reviewing code and doing some small fixes. Maybe add a CI to this repo.

**Comment by Aposhian** [comment]
> This package doesn't need any dependencies to build. It only contains headers. Therefore we move all find_package call to the BUILD_TEST section

I don't think that is ideal, since the headers for this package pull in PCL headers. Yes, building _this_ package doesn't need to find package PCL, but if you build a dependent package, then it's weird because you could only include headers from pcl_conversions, but then you would need to `find_package` PCL yourself. Normally calling `find_package` on dependenies shows up in the CMake package config file, and I believe that is what `build_export_depend` is intended to indicate.

> build_export_depend doesn't pull in the dependeny during build, only for dependent packages. Therefore we can also convert the PCL dependency to a \<build\> depend tag

It was a build depend before this PR was merged, and the build was broken then for a different reason.

**Comment by Aposhian** [comment]
Actually I think we may just be able to fix this by putting `libpcl-all-dev` as a `build_depend` _and_ a `build_export_depend`.

**Comment by SteveMacenski** [comment]
@cottsay @paulbovbel any objections to adding @Rayman as a co-maintainer on this? He's been active here for some time and I trust his judgement.

**Comment by Rayman** [comment]
Hmm, on further thought you still need to `find_package(PCL)` before you can `ament_export_dependencies(PCL)`. So a `<build_depend>` + `<build_export_depend>` seems the best indeed.

**Comment by SteveMacenski** [comment]
Fire up a PR and we can do this again 

:musical_note: Oh round, oh round we go :musical_note:

**Comment by Timple** [comment]
Cool, thanks @Rayman 

Would it be possible to re-bloom this @SteveMacenski ? :slightly_smiling_face:

**Comment by SteveMacenski** [comment]
:musical_note: Round and round we go :musical_note: 

https://github.com/ros/rosdistro/pull/41528

**Comment by Timple** [comment]
🎵 Oh round, oh round we go 🎵

Indeed :wink: 

I spend another day chasing a hard to find dependency issue:
https://github.com/autowarefoundation/autoware.universe/issues/9131

Turns out this has not been released for Jazzy. Would you mind a jazzy bloom @SteveMacenski ?

**Comment by SteveMacenski** [comment]
Hi ho. Sorry for the delay, we had ROSCon, ROS-I, and then I took a short vacation while in Europe. I'm getting back to work this morning :-)

@Rayman have you run a release yet or for a new distribution? This might be a good place to try it out. If not, I can give you some instructions if you're not familiar with the process. We basically need to branch off `jazzy` from  `ros2` and run bloom for `jazzy`. We just need to check that no major API/ABI breaking changes are on `jazzy` from when it was forked from `ros2` to break ABI/API, but I just looked and I don't think that's the case, so it should be a straight forward new-distribution bloom release.  

@Timple if @Rayman doesn't get back to us in a week or doesn't have the time, ping me again and I'll do it.

**Comment by Timple** [comment]
Well, no need for excuses to go on a holliday :smile: 

I'm happy to do the release as well. But neither I nor Rayman have access I guess: https://github.com/ros2-gbp/ros2-gbp-github-org/blob/130e2325ce8558570514efce7a9cc77a8c9288c2/perception.tf#L3

**Comment by SteveMacenski** [comment]
Please submit a PR to add it and tag me in. Steven Ragnarok should be able to easily merge that to give you access - though I think that's for Rayman. I don't think you have maintainer rights on this repo (... yet, wanna help? :wink: ) for you to also have release rights

**Comment by Timple** [comment]
I'll leave it to @Rayman for now :slightly_smiling_face:

**Comment by Rayman** [comment]
Hi @SteveMacenski,

I've looked at the commits that are now on the ros2 branch and I see that there are no breaking changes, only features. So my plan is as follows:

- Tag version 2.6.2 from the current ros2 branch
- Release this version in jazzy & rolling
- Keep releasing the ros2 branch to jazzy & rolling until we have a PR with a breaking feature

Is this OK?

**Comment by SteveMacenski** [comment]
You could do this yes. I would recommend branching now though for logistical reasons. Its easy to forget when merging a PR that is breaking ABI/API the status of the `ros2` branch and if it includes `jazzy` to remember to do the fork off then. Its better to do the fork immediately so that there's never a question about the state when merging into `ros2`. Otherwise, you can run bloom and re-release breaking changes or someone on the Jazzy distribution uses `ros2` branch for source builds and they have new build errors.

**Comment by Rayman** [comment]
I've created the 2.6.2 release tag. The next step is to bloom this for jazzy & rolling.

**Comment by Timple** [comment]
After: https://github.com/ros2-gbp/ros2-gbp-github-org/pull/635

**Pull request merged**
