### PR TITLE
Reformat license and copyright text for ament_copyright

### PR DESCRIPTION
**Pull request by theseankelly**
This is only a reformat so that ament_copyright picks up the text
correctly. There are no changes made to the license text or
copyright owner/year

Signed-off-by: Sean Kelly <sean@seankelly.dev>

### CODE REVIEW

**Comment by theseankelly** [comment]
@SteveMacenski this is the last of the one-off linter changes -- I'll rebase the transforms change (which also enables the package) next which will also take care cleaning `ament_xmllint` and `ament_lint_cmake`

**Comment by SteveMacenski** [comment]
So I'd be OK merging this, but this might be one worth just disabling that particular test

**Comment by theseankelly** [comment]
I kind of agree. I'll add the opt-out directive to the cmake file when I enable linting instead?

**Comment by SteveMacenski** [comment]
Yeah, that would work. I'm mostly concerned about cpplint, uncrustify, flake8 and cppcheck. Those are the "core code" ones that make the styling consistent. The copyright headers if missing always brings up a bunch of issues about who is the copyright holder. We could be opening ourselves to legal challenges if we mis-attribute the new headers

**Comment by theseankelly** [comment]
Great points, thanks @SteveMacenski -- closing request and stay tuned for some changes with real functionality ;)

**Pull request closed without merging**
