### PR TITLE
Use industrial_ci for travis testing

### PR DESCRIPTION
**Pull request by paulbovbel**
This might be a nicer option, I've been using industrial_ci for most of my other packages since it keeps all the travis/testing logic external to the repo under test.

### CODE REVIEW

**Review by wkentaro — APPROVED** [review]

**Comment by wkentaro** [comment]
I added the test on artful, too.

**Comment by wkentaro** [comment]
```
Errors     << pcl_ros:cmake /root/catkin_ws/logs/pcl_ros/build.cmake.000.log
** WARNING ** io features related to ensenso will be disabled
** WARNING ** io features related to davidSDK will be disabled
** WARNING ** io features related to dssdk will be disabled
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
** WARNING ** io features related to libusb-1.0 will be disabled
CMake Error at /root/catkin_ws/install/share/pcl_conversions/cmake/pcl_conversionsConfig.cmake:113 (message):
  Project 'pcl_conversions' specifies
  '/usr/include/x86_64-linux-gnu/freetype2' as an include dir, which is not
  found.  It does neither exist as an absolute directory nor in
  '/root/catkin_ws/install//usr/include/x86_64-linux-gnu/freetype2'.  Check
  the issue tracker
  'https://github.com/ros-perception/pcl_conversions/issues' and consider
  creating a ticket if the problem has not been reported yet.
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
  CMakeLists.txt:22 (find_package)
cd /root/catkin_ws/build/pcl_ros; catkin build --get-env pcl_ros | catkin env -si  /usr/bin/cmake /root/catkin_ws/src/perception_pcl/pcl_ros --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/root/catkin_ws/devel/.private/pcl_ros -DCMAKE_INSTALL_PREFIX=/root/catkin_ws/install; cd -
...............................................................................
Failed     << pcl_ros:cmake                        [ Exited with code 1 ]
Failed    <<< pcl_ros                              [ 2.7 seconds ]
[build] Successful packages:
 [   Ignored] perception_pcl 
[build] Failed packages:
 [    Failed] pcl_ros        
```
https://travis-ci.org/ros-perception/perception_pcl/jobs/373117791

**Comment by wkentaro** [comment]
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

It seems we need `travis_wait catkin build...`
https://travis-ci.org/ros-perception/perception_pcl/jobs/373117792

**Comment by paulbovbel** [comment]
@wkentaro I moved your travis_wait commit to travis-industrial-wkentaro, since i want to investigate further. If our build doesn't output anything for 10 minutes, it probably _is_ stalled.

**Comment by wkentaro** [comment]
I merged https://github.com/ros-perception/perception_pcl/pull/194, so I will do the rebase.

**Pull request closed without merging**
