### PR TITLE
Update common.py

### PR DESCRIPTION
**Pull request by rlklaser**
filters min max are bounded to only -5,5 when using rosparam load and dynamic reconfigure

### CODE REVIEW

**Comment by wjwwood** [comment]
I'll look at this tomorrow.

**Comment by wjwwood** [comment]
@jkammerl if you have time can you review this, to see if it is reasonable? I would imagine it is fine, but I don't know what affects this might have.

**Comment by jkammerl** [comment]
Hi @wjwwood, Yes, looks reasonable. In order to completely deactivate this filter by default, would it make sense to use sys.float_info.min/max as default value?

**Comment by wjwwood** [comment]
I think the defaults should be within the limits? Maybe I'm misunderstanding what you mean.

**Comment by wjwwood** [comment]
I don't really have any idea how this is being used internally, so I don't even know under what conditions this would "disable" the filter.

**Comment by wjwwood** [comment]
@rlklaser can you rebase against master (I fixed up the travis configs, so it should pass the automated tests now).

**Comment by jkammerl** [comment]
From briefly looking into the code, it looks like these are the default values for the passthrough and voxel grid filter nodelet. You are right, these default need to be within limits and therefore some large value should be fine.

**Pull request merged**
